config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new ,:create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    ## associate a list
    @bookmark.list = @list

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @list, notice: "bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private


  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "list was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


  private


  def list_params
    params.require(:list).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list,bookmark] do |f|%>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= render 'form', list: @list,bookmark: @bookmark  %>
<%= link_to 'Back', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<% @lists.each do |list| %>
<%= list.name %>
<% end %>

<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for @list do |f| %>
<%= f.input :name %>
<%= f.submit %>
<% end %>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<%= @list.name %>

<% @list.movies.each do |movie| %>
  <%= movie.title %>
<% end %>


<%= link_to "Add a Bookmark", new_list_bookmark_path(@list,@bookmark) %>